/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Avisos del usuario
         * @description Los más recientes primero. El contador de pendientes viene aparte, porque no depende de cuántos se hayan pedido.
         */
        get: operations["NotificationsController_list"];
        put?: never;
        post?: never;
        /**
         * Purgar
         * @description Sin identificadores, vacía todos los leídos. Borrar un aviso no toca el comentario ni la versión a la que apuntaba (RF-909, RF-911).
         */
        delete: operations["NotificationsController_purge"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/notifications/read": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Marcar como leídos
         * @description Sin cuerpo, marca todos los pendientes (RF-903).
         */
        post: operations["NotificationsController_markRead"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Buscar apps
         * @description Por nombre, descripción, etiquetas y contenido de la visión, en todos los workspaces del usuario. Cada resultado dice de cuál viene (RF-604).
         */
        get: operations["SearchController_buscar"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Cuentas de la instancia
         * @description Rol, estado y actividad. En cuántos workspaces está cada uno, no en cuáles.
         */
        get: operations["AdminController_users"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar rol o estado de una cuenta
         * @description La instancia nunca puede quedarse sin administrador activo, y desactivar cierra las sesiones abiertas (RF-202, RF-203).
         */
        patch: operations["AdminController_update"];
        trace?: never;
    };
    "/api/v1/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Métricas de la instancia
         * @description Números agregados, sin acceder al contenido de ningún workspace (RF-204).
         */
        get: operations["AdminController_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Auditoría de plataforma
         * @description Altas, sesiones y roles. Lo que ocurre dentro de un workspace es de su dueño (RF-703, RF-704).
         */
        get: operations["AdminController_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/github": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Iniciar sesión con GitHub */
        get: operations["AuthController_signIn"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cerrar sesión */
        post: operations["AuthController_logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quién soy */
        get: operations["AuthController_me"];
        put?: never;
        post?: never;
        /**
         * Darse de baja
         * @description Apaga la cuenta y arranca el plazo de gracia: nada se borra, y volver a entrar dentro del plazo la reactiva. El borrado definitivo lo ejecuta un administrador (RF-207).
         */
        delete: operations["AuthController_deactivate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Workspaces a los que pertenezco */
        get: operations["WorkspacesController_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar el nombre o el aspecto de un workspace propio */
        patch: operations["WorkspacesController_update"];
        trace?: never;
    };
    "/api/v1/workspaces/{id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Miembros del workspace */
        get: operations["WorkspacesController_members"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Expulsar a un miembro */
        delete: operations["WorkspacesController_removeMember"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/leave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Abandonar un workspace ajeno */
        post: operations["WorkspacesController_leave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/audit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Actividad del workspace
         * @description Solo para su dueño. Registra qué pasó, nunca qué decía: ni contenido ni credenciales (RF-704, RF-706).
         */
        get: operations["WorkspacesController_audit"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{id}/invitations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Invitaciones del workspace */
        get: operations["WorkspacesController_invitations"];
        put?: never;
        /**
         * Invitar por email
         * @description La respuesta es idéntica exista o no una cuenta con ese email: invitar no sirve para averiguar quién usa la plataforma.
         */
        post: operations["WorkspacesController_invite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/invitations/{invitationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revocar una invitación */
        delete: operations["WorkspacesController_revoke"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workspaces/{workspaceId}/apps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Apps visibles del workspace */
        get: operations["AppsController_list"];
        put?: never;
        /**
         * Crear una app
         * @description Nace con su documento de visión listo. Lo que crea un invitado en un workspace ajeno queda en WORKSPACE_WRITE.
         */
        post: operations["AppsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ficha de una app */
        get: operations["AppsController_get"];
        put?: never;
        post?: never;
        /** Eliminar la app y todo su historial */
        delete: operations["AppsController_remove"];
        options?: never;
        head?: never;
        /** Editar metadatos */
        patch: operations["AppsController_update"];
        trace?: never;
    };
    "/api/v1/apps/{id}/access-level": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar el nivel de acceso */
        patch: operations["AppsController_changeAccessLevel"];
        trace?: never;
    };
    "/api/v1/apps/{id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archivar */
        post: operations["AppsController_archive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Desarchivar */
        post: operations["AppsController_unarchive"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{id}/transfer-precursor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Transferir el rol de precursor */
        post: operations["AppsController_transfer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Documento de visión actual */
        get: operations["DocumentsController_get"];
        /**
         * Guardar una versión nueva
         * @description Hay que enviar la versión desde la que se editó. Si alguien guardó mientras tanto, se responde 409 con lo que hay ahora en lugar de sobrescribirlo.
         */
        put: operations["DocumentsController_save"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Historial de versiones */
        get: operations["DocumentsController_versions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document/versions/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Una versión concreta, con su contenido */
        get: operations["DocumentsController_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document/diff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Dos versiones para comparar
         * @description Devuelve ambos contenidos; el cálculo visual de diferencias es cosa del cliente.
         */
        get: operations["DocumentsController_diff"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document/restore/{versionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Restaurar una versión anterior
         * @description Crea una versión nueva con ese contenido. No borra nada.
         */
        post: operations["DocumentsController_restore"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document/contributors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Quiénes han escrito en esta visión */
        get: operations["DocumentsController_contributors"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/document/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Descargar como VISION.md */
        get: operations["DocumentsController_export"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/threads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hilos de comentarios de una app
         * @description Devuelve todos, incluidos los resueltos: la interfaz decide qué enseña.
         */
        get: operations["CommentsController_list"];
        put?: never;
        /**
         * Abrir un hilo
         * @description Con fragmento y posición, el hilo queda anclado al texto; sin ellos, es un hilo general.
         */
        post: operations["CommentsController_createThread"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/apps/{appId}/mentionable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * A quién se puede mencionar
         * @description Solo miembros del workspace: mencionar no revela quién más usa la plataforma.
         */
        get: operations["CommentsController_mentionable"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Responder en un hilo */
        post: operations["CommentsController_reply"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dar por resuelto un hilo */
        post: operations["CommentsController_resolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}/reopen": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reabrir un hilo resuelto */
        post: operations["CommentsController_reopen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/threads/{threadId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Borrar un hilo entero */
        delete: operations["CommentsController_removeThread"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Borrar un comentario propio
         * @description El hilo conserva su forma: se marca como borrado, no se elimina.
         */
        delete: operations["CommentsController_remove"];
        options?: never;
        head?: never;
        /** Editar un comentario propio */
        patch: operations["CommentsController_edit"];
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness: el proceso responde */
        get: operations["HealthController_live"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness: las dependencias responden */
        get: operations["HealthController_ready"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        NotificationDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "WORKSPACE_INVITED" | "APP_COMMENTED" | "THREAD_REPLIED" | "THREAD_RESOLVED" | "MENTIONED" | "DOCUMENT_VERSION_SAVED" | "PRECURSOR_TRANSFERRED" | "APPS_INHERITED";
            /** @description Lo necesario para pintar el aviso sin más consultas. Es una foto del momento: si el comentario se borra después, el aviso sigue leyéndose. */
            payload: {
                [key: string]: unknown;
            };
            /** Format: uuid */
            workspaceId: string;
            /** Format: uuid */
            appId: string | null;
            /** Format: uuid */
            threadId: string | null;
            /** Format: date-time */
            readAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationListDto: {
            items: components["schemas"]["NotificationDto"][];
            /** @description Sin leer. Es el número del contador, y no depende de cuántas se hayan pedido. */
            unread: number;
        };
        MarkReadDto: {
            /** @description Cuáles marcar. Si se omite, se marcan todas las pendientes. */
            ids?: string[];
        };
        AppIconDto: {
            /** @description Emoji de la selección curada */
            emoji: string;
            /** @description Color de fondo de la paleta */
            color: string;
        };
        SearchHitDto: {
            /** Format: uuid */
            id: string;
            name: string;
            shortDescription: string | null;
            status: string;
            accessLevel: string;
            icon: components["schemas"]["AppIconDto"];
            isArchived: boolean;
            /**
             * Format: uuid
             * @description De dónde viene el resultado: la búsqueda cruza workspaces (RF-604).
             */
            workspaceId: string;
            workspaceName: string;
            /** @description Trozo del texto donde aparece lo buscado, con las coincidencias marcadas. */
            excerpt: string | null;
        };
        SearchResultsDto: {
            items: components["schemas"]["SearchHitDto"][];
            /** @description Lo que se buscó, ya normalizado */
            query: string;
        };
        AdminUserDto: {
            /** Format: uuid */
            id: string;
            handle: string;
            displayName: string;
            avatarUrl: string | null;
            /** @enum {string} */
            platformRole: "ADMIN" | "MEMBER";
            /** @enum {string} */
            status: "ACTIVE" | "DEACTIVATED";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt: string | null;
            /** @description En cuántos workspaces está, sin decir cuáles (D-6). */
            workspaceCount: number;
            /** @description Si es la propia cuenta de quien consulta. */
            isMe: boolean;
        };
        UpdateUserDto: {
            /** @enum {string} */
            platformRole?: "ADMIN" | "MEMBER";
            /** @enum {string} */
            status?: "ACTIVE" | "DEACTIVATED";
        };
        InstanceMetricsDto: {
            usersTotal: number;
            usersActive: number;
            workspacesTotal: number;
            appsTotal: number;
            appsArchived: number;
            versionsTotal: number;
            threadsOpen: number;
        };
        AuditEntryDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            actorId: string | null;
            actorHandle: string | null;
            action: string;
            resourceType: string | null;
            /** Format: uuid */
            resourceId: string | null;
            /** @description Identificadores y valores de enum. Nunca contenido (RF-706). */
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        CurrentUserDto: {
            /** Format: uuid */
            id: string;
            /** @description Nombre de usuario de GitHub, usado en las menciones */
            handle: string;
            email: string;
            displayName: string;
            avatarUrl: string | null;
            /** @enum {string} */
            platformRole: "ADMIN" | "MEMBER";
        };
        WorkspaceDto: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /**
             * @description Rol de quien consulta en este workspace
             * @enum {string}
             */
            role: "OWNER" | "MEMBER";
            /** @description Si es el workspace personal de su dueño */
            isPersonal: boolean;
            iconEmoji: string;
            iconColor: string;
            /** @description Fondo elegido del catálogo */
            background: string;
        };
        UpdateWorkspaceDto: {
            name?: string;
            /** @enum {string} */
            iconEmoji?: "🗂️" | "🏠" | "🧭" | "⚗️" | "🌳" | "🛰️" | "🏛️" | "🎪" | "⛺" | "🌋" | "🗼" | "🧵" | "🪴" | "🧊" | "🎠" | "🛖";
            /** @enum {string} */
            iconColor?: "amber" | "rose" | "violet" | "indigo" | "sky" | "teal" | "emerald" | "lime" | "orange" | "slate";
            /**
             * @description Identificador del fondo; el catálogo vive en la interfaz.
             * @enum {string}
             */
            background?: "plain" | "dawn" | "dusk" | "forest" | "ocean" | "ember" | "grid" | "dots";
        };
        MemberDto: {
            /** Format: uuid */
            userId: string;
            handle: string;
            displayName: string;
            avatarUrl: string | null;
            /** @enum {string} */
            role: "OWNER" | "MEMBER";
        };
        WorkspaceAuditEntryDto: {
            /** Format: uuid */
            id: string;
            actorHandle: string | null;
            /** @description Qué se hizo, en forma de identificador estable. */
            action: string;
            resourceType: string | null;
            /** Format: uuid */
            resourceId: string | null;
            /** @description Identificadores y valores de enum. Nunca contenido (RF-706). */
            metadata: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        InvitationDto: {
            /** Format: uuid */
            id: string;
            email: string;
            /** @enum {string} */
            status: "PENDING" | "ACCEPTED" | "REVOKED" | "EXPIRED";
            /** Format: date-time */
            expiresAt: string;
            /** Format: date-time */
            createdAt: string;
        };
        InviteDto: {
            /**
             * Format: email
             * @description Email de la persona a invitar
             */
            email: string;
        };
        CreateAppDto: {
            name: string;
            shortDescription?: string;
            /**
             * @description Solo lo elige el dueño del workspace. Lo que crea un invitado queda en WORKSPACE_WRITE.
             * @enum {string}
             */
            accessLevel?: "PRIVATE" | "WORKSPACE_READ" | "WORKSPACE_WRITE";
        };
        AppSummaryDto: {
            /** Format: uuid */
            id: string;
            slug: string;
            name: string;
            shortDescription: string | null;
            /** @enum {string} */
            status: "IDEA" | "DEFINING" | "IN_DEVELOPMENT" | "PUBLISHED" | "PAUSED" | "ARCHIVED";
            /** @enum {string} */
            accessLevel: "PRIVATE" | "WORKSPACE_READ" | "WORKSPACE_WRITE";
            icon: components["schemas"]["AppIconDto"];
            tags: string[];
            repoUrl: string | null;
            /** @description Handle de GitHub de quien la creó */
            precursorHandle: string;
            /** @description Si quien consulta es su precursor */
            isPrecursor: boolean;
            /** @description Si quien consulta puede editarla */
            canEdit: boolean;
            isArchived: boolean;
            /** @description Conversaciones abiertas sobre la app (RF-811). */
            openThreads: number;
            /** Format: date-time */
            updatedAt: string;
        };
        AppListDto: {
            items: components["schemas"]["AppSummaryDto"][];
            /** @description Cuántas hay en total con estos filtros, no cuántas trae esta página. */
            total: number;
            page: number;
            perPage: number;
            /** @description Todas las etiquetas usadas en el workspace, para poder ofrecer el filtro sin una consulta aparte. */
            availableTags: string[];
        };
        UpdateAppDto: {
            name?: string;
            shortDescription?: string | null;
            /** @enum {string} */
            status?: "IDEA" | "DEFINING" | "IN_DEVELOPMENT" | "PUBLISHED" | "PAUSED" | "ARCHIVED";
            tags?: string[];
            /** @description Enlace al repositorio. Informativo: no sincroniza nada todavía (RF-417). */
            repoUrl?: string;
            /** @enum {string} */
            iconEmoji?: "💡" | "✨" | "🌱" | "🔮" | "🚀" | "🧭" | "🛠️" | "⚙️" | "🧰" | "🔧" | "📐" | "🧪" | "📚" | "📝" | "🧠" | "🔍" | "🗺️" | "📊" | "💬" | "📣" | "📨" | "🤝" | "🎙️" | "📡" | "🏗️" | "🧱" | "🗂️" | "🎛️" | "🪟" | "🧩" | "🌊" | "🌲" | "⛰️" | "🌙" | "☀️" | "⏳" | "🎯" | "🎲" | "🎨" | "🎵" | "🏔️" | "🔥";
            /** @enum {string} */
            iconColor?: "amber" | "rose" | "violet" | "indigo" | "sky" | "teal" | "emerald" | "lime" | "orange" | "slate";
        };
        ChangeAccessLevelDto: {
            /** @enum {string} */
            accessLevel: "PRIVATE" | "WORKSPACE_READ" | "WORKSPACE_WRITE";
        };
        TransferPrecursorDto: {
            /**
             * Format: uuid
             * @description Miembro del workspace que pasa a ser precursor
             */
            userId: string;
        };
        DocumentDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            type: "VISION" | "PRD" | "TRD";
            content: string;
            /**
             * Format: uuid
             * @description Versión sobre la que se está editando. Hay que devolverla al guardar.
             */
            currentVersionId: Record<string, never> | null;
            versionNo: number;
            canEdit: boolean;
            /** Format: date-time */
            updatedAt: string;
        };
        SaveDocumentDto: {
            /** @description Contenido completo en markdown */
            content: string;
            /**
             * Format: uuid
             * @description Versión desde la que se editó. Si mientras tanto alguien guardó otra, la petición se rechaza con 409 en lugar de sobrescribir.
             */
            baseVersionId: string;
            /** @description Qué cambió y por qué */
            message?: string;
        };
        ConflictDto: {
            /** @example 409 */
            statusCode: number;
            message: string;
            /** @description Contenido que hay ahora mismo guardado */
            currentContent: string;
            /** Format: uuid */
            currentVersionId: string;
            currentVersionNo: number;
            /** @description Quién guardó mientras tanto */
            lastAuthorHandle: string;
        };
        VersionSummaryDto: {
            /** Format: uuid */
            id: string;
            versionNo: number;
            authorHandle: string;
            authorDisplayName: string;
            message: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        VersionDetailDto: {
            /** Format: uuid */
            id: string;
            versionNo: number;
            authorHandle: string;
            authorDisplayName: string;
            message: string | null;
            /** Format: date-time */
            createdAt: string;
            content: string;
        };
        DiffDto: {
            from: components["schemas"]["VersionDetailDto"];
            to: components["schemas"]["VersionDetailDto"];
        };
        ContributorDto: {
            /** Format: uuid */
            userId: string;
            handle: string;
            displayName: string;
            avatarUrl: string | null;
            /** @description Cuántas versiones ha escrito */
            versionCount: number;
        };
        CommentDto: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            parentId: string | null;
            /** @description Vacío si el comentario fue borrado */
            body: string;
            authorHandle: string;
            authorDisplayName: string;
            authorAvatarUrl: string | null;
            isMine: boolean;
            isDeleted: boolean;
            isEdited: boolean;
            /** @description Handles mencionados */
            mentions: string[];
            /** Format: date-time */
            createdAt: string;
        };
        ThreadDto: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            kind: "GENERAL" | "INLINE";
            /** @enum {string} */
            status: "OPEN" | "RESOLVED";
            /**
             * @description Solo en hilos inline. Huérfano cuando su fragmento ya no existe.
             * @enum {string|null}
             */
            anchorStatus: "ANCHORED" | "ORPHANED" | null;
            /** @description Fragmento comentado */
            anchorQuote: string | null;
            anchorStart: number | null;
            anchorEnd: number | null;
            /** @description Quién lo resolvió */
            resolvedByHandle: string | null;
            canDelete: boolean;
            comments: components["schemas"]["CommentDto"][];
            /** Format: date-time */
            createdAt: string;
        };
        CreateThreadDto: {
            body: string;
            /** @description Fragmento comentado. Si falta, el hilo es general. */
            quote?: string;
            /** @description Posición inicial del fragmento en el markdown */
            start?: number;
            end?: number;
        };
        MentionableUserDto: {
            /** Format: uuid */
            userId: string;
            handle: string;
            displayName: string;
            avatarUrl: string | null;
        };
        CreateCommentDto: {
            body: string;
            /**
             * Format: uuid
             * @description Comentario al que responde
             */
            parentId?: string;
        };
        UpdateCommentDto: {
            body: string;
        };
        DependencyCheckDto: {
            /**
             * @description Estado de la dependencia
             * @enum {string}
             */
            status: "up" | "down";
            /**
             * @description Tiempo de respuesta en milisegundos
             * @example 12
             */
            latencyMs: number;
            /** @description Motivo del fallo, si lo hubo */
            error?: string;
        };
        LivenessDto: {
            /** @enum {string} */
            status: "ok";
        };
        ReadinessReportDto: {
            /** @enum {string} */
            status: "ok" | "degraded";
            /** @description Una entrada por dependencia comprobada */
            checks: {
                [key: string]: components["schemas"]["DependencyCheckDto"];
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    NotificationsController_list: {
        parameters: {
            query?: {
                /** @description Cuántos devolver. Por defecto 30, y como mucho 100. */
                limit?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListDto"];
                };
            };
        };
    };
    NotificationsController_purge: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListDto"];
                };
            };
        };
    };
    NotificationsController_markRead: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MarkReadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationListDto"];
                };
            };
        };
    };
    SearchController_buscar: {
        parameters: {
            query?: {
                /** @description Qué buscar */
                q?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResultsDto"];
                };
            };
        };
    };
    AdminController_users: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"][];
                };
            };
        };
    };
    AdminController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateUserDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminUserDto"];
                };
            };
        };
    };
    AdminController_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceMetricsDto"];
                };
            };
        };
    };
    AdminController_audit: {
        parameters: {
            query?: {
                /** @description Quién lo hizo */
                actorId?: string;
                /** @description Desde, en ISO 8601 */
                from?: string;
                /** @description Hasta, en ISO 8601 */
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEntryDto"][];
                };
            };
        };
    };
    AuthController_signIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AuthController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CurrentUserDto"];
                };
            };
        };
    };
    AuthController_deactivate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDto"][];
                };
            };
        };
    };
    WorkspacesController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateWorkspaceDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDto"];
                };
            };
        };
    };
    WorkspacesController_members: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberDto"][];
                };
            };
        };
    };
    WorkspacesController_removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_leave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    WorkspacesController_audit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceAuditEntryDto"][];
                };
            };
        };
    };
    WorkspacesController_invitations: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationDto"][];
                };
            };
        };
    };
    WorkspacesController_invite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InviteDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvitationDto"];
                };
            };
        };
    };
    WorkspacesController_revoke: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                invitationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppsController_list: {
        parameters: {
            query?: {
                /** @description Estados separados por comas, p. ej. `IDEA,DEFINING` */
                status?: string;
                /** @description Niveles de acceso separados por comas */
                accessLevel?: string;
                /** @description Etiquetas separadas por comas; se exigen todas */
                tag?: string;
                /** @description Las archivadas se ocultan salvo que se pidan. */
                archived?: "hide" | "only" | "all";
                sort?: "updated" | "name";
                /** @description Desde 1 */
                page?: string;
                /** @description Por defecto 24, como mucho 100 */
                perPage?: string;
            };
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppListDto"];
                };
            };
        };
    };
    AppsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workspaceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAppDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    AppsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    AppsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    AppsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAppDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    AppsController_changeAccessLevel: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangeAccessLevelDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    AppsController_archive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    AppsController_unarchive: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    AppsController_transfer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransferPrecursorDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AppSummaryDto"];
                };
            };
        };
    };
    DocumentsController_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
        };
    };
    DocumentsController_save: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SaveDocumentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConflictDto"];
                };
            };
        };
    };
    DocumentsController_versions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionSummaryDto"][];
                };
            };
        };
    };
    DocumentsController_version: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionDetailDto"];
                };
            };
        };
    };
    DocumentsController_diff: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiffDto"];
                };
            };
        };
    };
    DocumentsController_restore: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
                versionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDto"];
                };
            };
        };
    };
    DocumentsController_contributors: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContributorDto"][];
                };
            };
        };
    };
    DocumentsController_export: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_list: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDto"][];
                };
            };
        };
    };
    CommentsController_createThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateThreadDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDto"];
                };
            };
        };
    };
    CommentsController_mentionable: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                appId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MentionableUserDto"][];
                };
            };
        };
    };
    CommentsController_reply: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentDto"];
                };
            };
        };
    };
    CommentsController_resolve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDto"];
                };
            };
        };
    };
    CommentsController_reopen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThreadDto"];
                };
            };
        };
    };
    CommentsController_removeThread: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                threadId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CommentsController_edit: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                commentId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCommentDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CommentDto"];
                };
            };
        };
    };
    HealthController_live: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessDto"];
                };
            };
        };
    };
    HealthController_ready: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReportDto"];
                };
            };
            /** @description Alguna dependencia falla */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessReportDto"];
                };
            };
        };
    };
}
